stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/external/uber.csv

  data_processing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/external/uber.csv
    - src/data/data_preprocessing.py
    outs:
    - data/raw/driver_acceptance_data.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/raw/driver_acceptance_data.csv
    - src/features/feature_engineering.py
    - src/features/missing_value_imputer.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed/train.csv
    - src/models/model_building.py
    - params.yaml
    params:
    - model_building.learning_rate
    - model_building.n_estimators
    - model_building.num_leaves
    - model_building.min_child_samples
    - model_building.subsample
    - model_building.colsample_bytree
    - model_building.reg_alpha
    - model_building.reg_lambda
    - model_building.class_weight
    - model_building.random_state
    outs:
    - models/lightgbm_model.pkl
    - models/scaler.pkl
  
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - models/lightgbm_model.pkl
    - models/scaler.pkl
    - src/models/model_evaluation.py
    - data/processed/test.csv
    - src/models/classification_evaluator.py
    outs:
    - reports/evaluation_report.json